/**
 * Common prompt definitions used across different configuration files
 */

export const PYTHON_SLASH_COMMAND = {
  name: "python",
  description:
    "Generate Python code using python_code_gen tool (use generated code as-is)",
  prompt: `{{{ input }}}

For Python code generation, you MUST use the python_code_gen tool to generate complete, runnable Python code. CRITICAL: Do not modify, change, or rewrite the generated code in any way. Use the generated code exactly as it is – copy and apply it directly without any modifications. 

- Do NOT add or remove any code beyond what is generated.
- Do NOT add explanations, comments, import statements, type hints, docstrings, test code, or example code unless they are already present in the generated code.
- Do NOT change variable names, code structure, or formatting.
- If input contains test cases, docstrings, or comments, these must be kept exactly as generated by the code generation tool.
- If the input does NOT contain test code, do NOT generate or add any tests.
- The output must be code only, with the exact content as generated, with no added or omitted text.

The generated code must be used as-is, including all comments, docstrings, and test cases, and must not include any modifications or additions beyond what is produced by the python_code_gen tool.`,
};

export const PYTHON_SLASH_COMMAND_YAML = `  - name: python
    description: Generate Python code using python_code_gen tool (use generated code as-is)
    prompt: |
      {{{ input }}}

      For Python code generation, you MUST use the python_code_gen tool to generate complete, runnable Python code. CRITICAL: Do not modify, change, or rewrite the generated code in any way. Use the generated code exactly as it is – copy and apply it directly without any modifications. 

      - Do NOT add or remove any code beyond what is generated.
      - Do NOT add explanations, comments, import statements, type hints, docstrings, test code, or example code unless they are already present in the generated code.
      - Do NOT change variable names, code structure, or formatting.
      - If input contains test cases, docstrings, or comments, these must be kept exactly as generated by the code generation tool.
      - If the input does NOT contain test code, do NOT generate or add any tests.
      - The output must be code only, with the exact content as generated, with no added or omitted text.

      The generated code must be used as-is, including all comments, docstrings, and test cases, and must not include any modifications or additions beyond what is produced by the python_code_gen tool.`;
